default: &default
adapter: postgresql
encoding: unicode
pool: 5

development:
<<: *default
database: makersbnb

production:
<<: *default
database: makersbnb

test:
<<: *default
database: makersbnb_test